### ISSUE TITLE
Developing Agents for the Mini-game

### ISSUE THREAD

**Issue by heerdemoglu** [heerdemoglu/Minigame_Hit_and_Run#1]
Scripted and RL based agents should be written for the minigame. Current RL methods include Q-Learning, Temporal Difference Learning, and Multi-Armed Bandit problems.

**Comment by SoyGema** [comment]
Ey @heerdemoglu !
Welcome to GitHub and awesome growing #pySC2 community 
I encourage you to open the project theme for this topic ^^
https://github.com/heerdemoglu/Minigame_Hit_and_Run/projects

Have an awesome time making Starcraft II playing agent !

**Comment by heerdemoglu** [comment]
Hey @SoyGema!

Thank you for your warm welcome to the community.

Getting used to GitHub is a steep learning progress for me. Thank you for your advice. I am opening a project on this topic. I will close this issue and move to project section.
